load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "thunder",
    srcs = [
        "thunder.go",
        "clients.go",
        "doc.go",
        "enrollment.go",
        "errors.go",
        "servers.go",
        "paths.go",
        "zones.go",
    ],
    embedsrcs = ["endpoints.json"],
    importpath = "github.com/Thunder-Compute/thunder-sdk",
    visibility = ["//visibility:public"],
)

go_test(
    name = "thunder_test",
    srcs = ["client_test.go"],
    embed = [":thunder"],
)
